apiVersion: v1
kind: Service
metadata:
  name: ocpp-csms-service
  namespace: default
  labels:
    app: ocpp-csms
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: http
    protocol: TCP
  selector:
    app: ocpp-csms
  sessionAffinity: ClientIP  # Important for WebSocket connections
