name: Build Docker Container

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Set build variables
      id: vars
      run: |
        echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_OUTPUT
        echo "BUILD_SOURCE_VERSION=${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "BUILD_TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_NUMBER=${{ steps.vars.outputs.BUILD_NUMBER }}
          BUILD_SOURCE_VERSION=${{ steps.vars.outputs.BUILD_SOURCE_VERSION }}
          BUILD_TIMESTAMP=${{ steps.vars.outputs.BUILD_TIMESTAMP }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image details
      run: |
        echo "Image tags: ${{ steps.meta.outputs.tags }}"
        echo "Image digest: ${{ steps.build.outputs.digest }}"
